### ISSUE TITLE
update the mini site's copyright from 2023 to 2024

### ISSUE THREAD

**Issue by lyou** [foss-for-synopsys-dwc-arc-processors/arc-v-getting-started#3]
update the mini site's copyright from 2023 to 2024

**Comment by abrodkin** [comment]
Thanks for the report, will fix it now!

**Comment by abrodkin** [comment]
Fixed with https://github.com/foss-for-synopsys-dwc-arc-processors/arc-v-getting-started/commit/a2509f9ed589e4909de2903beaa5fae3454ae0df
